- name: Get dockerhub token
  no_log: true
  uri:
    url: "https://auth.docker.io/token?service=registry.docker.io&scope=repository:{{ image.repository }}:pull,push"
    user: "{{ docker_credentials.username }}"
    password: "{{ docker_credentials.password }}"
    force_basic_auth: true
  register: token
- name: Retag image
  loop: "{{ image.tags | default(['latest']) }}"
  loop_control:
    loop_var: image_tag
  include_tasks: promote-retag-inner.yaml
